import path from "node:path";
import fs from "fs-extra";
import type { ParsedFile } from "../types.js";
import { detectLanguage } from "../utils/language.js";
import { formatTokenCount } from "../utils/tokens.js";

export interface MarkdownExportOptions {
  outputPath: string;
  title: string;
  inputDir: string;
  generatedAt: string;
}

export async function exportCombinedMarkdown(
  files: ParsedFile[],
  options: MarkdownExportOptions,
): Promise<void> {
  const lines: string[] = [];

  lines.push(`# ${options.title}`);
  lines.push("");
  lines.push(
    `> Generated by **ai-contextify** on ${options.generatedAt}.`,
    `> Source: \`${options.inputDir}\``,
    `> Files: ${files.length} · Total tokens (est.): ${formatTokenCount(
      files.reduce((acc, f) => acc + f.estimatedTokens, 0),
    )}`,
  );
  lines.push("");
  lines.push("## Table of contents");
  lines.push("");
  for (const file of files) {
    const anchor = anchorFor(file.relativePath);
    lines.push(
      `- [\`${file.relativePath}\`](#${anchor}) — ${file.kind} · ${formatTokenCount(file.estimatedTokens)} tok`,
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const file of files) {
    lines.push(`## \`${file.relativePath}\``);
    lines.push("");
    lines.push(
      `- **Kind:** ${file.kind}`,
      `- **Size:** ${file.bytes} bytes`,
      `- **Estimated tokens:** ${file.estimatedTokens}`,
    );
    if (file.parseError) {
      lines.push(`- **Parse error:** ${file.parseError}`);
    }
    lines.push("");

    lines.push(renderBody(file));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  await fs.ensureDir(path.dirname(options.outputPath));
  await fs.writeFile(options.outputPath, lines.join("\n"), "utf8");
}

function renderBody(file: ParsedFile): string {
  if (!file.content.trim()) return "_(empty)_";

  if (file.kind === "markdown") return file.content.trim();

  if (file.kind === "code" || file.kind === "json") {
    const lang =
      file.language ?? detectLanguage(file.extension, file.relativePath);
    return wrapFence(file.content, lang);
  }

  // pdf / docx / text / unknown → render as plain text block.
  return file.content.trim();
}

function wrapFence(content: string, language: string): string {
  // Pick a fence longer than any run of backticks in the content.
  const longestBacktickRun = (content.match(/`+/g) ?? [])
    .reduce((max, run) => Math.max(max, run.length), 0);
  const fenceLength = Math.max(3, longestBacktickRun + 1);
  const fence = "`".repeat(fenceLength);
  return `${fence}${language}\n${content.replace(/\s+$/, "")}\n${fence}`;
}

function anchorFor(relPath: string): string {
  return relPath
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
